ALTER PROCEDURE [dbo].[SP_RETORNA_DADOS_CLIENTE]
AS
BEGIN

	SELECT
		NR_CLIENTE,
		TX_CPF,
		NM_CLIENTE,
		DT_NASC
	INTO #TEMP_DADOS
	FROM TB_DADOS_CLIENTE

	DECLARE @SSQL VARCHAR(MAX) = '
	SELECT *
	FROM TB_DADOS_CLIENTE'

	EXEC(@SSQL)

END

alter PROCEDURE [dbo].[SP_ERRO_DE_LOGICA]
AS
BEGIN

	DECLARE @QTD INT = 1

	CREATE TABLE #TEMP_DADOS(NR_CLIENTE INT)

	WHILE @QTD <= 10
	BEGIN

		INSERT INTO #TEMP_DADOS VALUES(@QTD)
		set @QTD = @QTD + 1;
	END

END


CREATE TABLE TB_DADOS(ID_DADO INT PRIMARY KEY IDENTITY(1,1),
					  NM_DADO VARCHAR(100) NOT NULL,
					  BT_ATIVO BIT NOT NULL,
					  NM_USUARIO_CADASTRO VARCHAR(1000) NOT NULL,
					  DT_CADASTRO DATETIME);



					  
CREATE PROCEDURE [dbo].[SP_INSERE_DADOS](@ID_DADO int,
									@NM_DADO VARCHAR(100),
									@BT_ATIVO BIT,
									@NM_USUARIO_CADASTRO VARCHAR(1000),
									@DT_CADASTRO DATETIME = NULL)
AS
BEGIN 

	IF EXISTS(select 1 from TB_DADOS WHERE ID_DADO = @ID_DADO)
	BEGIN
		UPDATE TB_DADOS SET NM_DADO = @NM_DADO,
							BT_ATIVO = @BT_ATIVO,
							NM_USUARIO_CADASTRO = @NM_USUARIO_CADASTRO,
							DT_CADASTRO = @DT_CADASTRO
	END
	ELSE
	BEGIN
		INSERT INTO TB_DADOS(NM_DADO,BT_ATIVO ,NM_USUARIO_CADASTRO,DT_CADASTRO)
		SELECT @NM_DADO,
			   @BT_ATIVO,
			   @NM_USUARIO_CADASTRO,
			   @DT_CADASTRO		
	END
END

CREATE VIEW [dbo].[VW_RETORNA_DADOS]
AS

	SELECT *
	FROM TB_DADOS
	WHERE BT_ATIVO = 1



CREATE FUNCTION FN_RETORNA_DIA_SEMANA  (@DATA DATETIME) RETURNS VARCHAR (20)  AS
BEGIN
  DECLARE @DIA INT,
   @DIA_EXT VARCHAR(20)
   
  SELECT @DIA = (DATEPART(DW,@DATA ))
   IF @DIA=1 
    SET @DIA_EXT ='DOMINGO'
  IF @DIA=2  
     SET @DIA_EXT ='SEGUNDA-FEIRA'
  IF @DIA=3  
     SET @DIA_EXT ='TERÇA-FEIRA'
  IF @DIA=4  
     SET @DIA_EXT ='QUARTA-FEIRA'
  IF @DIA=5  
     SET @DIA_EXT ='QUINTA-FEIRA'
  IF @DIA=6  
     SET @DIA_EXT ='SEXTA-FEIRA'
  IF @DIA=7  
     SET @DIA_EXT ='SÁBADO'
   RETURN @DIA_EXT
END

DECLARE @LOTE INT = 10
WHILE(EXISTS(SELECT 1 FROM TB_PROCESSAMENTO  WHERE BT_EXECUTADO = 0))
BEGIN
UPDATE TOP (10) TB_PROCESSAMENTO SET BT_EXECUTADO = 1, NR_LOTE = @LOTE WHERE BT_EXECUTADO = 0
SET @LOTE = @LOTE + 10
END



